/*
    PROJECT EULER : PROBLEM 2
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    Find the sum of all the even-valued terms in the sequence which do not exceed four million.

*/
#include <iostream>
using namespace std;
 
int main(){
    int oldNumber=0,newNumber=1,sum=0,n,x=4000000;
    while(sum <= x)
    {
        n = oldNumber + newNumber;
        oldNumber = newNumber;
        newNumber = n;
        if(n%2 == 0)
        {
            sum = sum + n;
        }
    }
    cout << "result = " << sum;
}